--DROP TABLE IF EXISTS "Friends";
--DROP TABLE IF EXISTS "FilmLikes";
--DROP TABLE IF EXISTS "FilmGenre";
--DROP TABLE IF EXISTS "Film";
--DROP TABLE IF EXISTS "User";

CREATE TABLE IF NOT EXISTS "Rating"  (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE IF NOT EXISTS "Genre"(
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" varchar
);

CREATE TABLE IF NOT EXISTS "User"(
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar,
  "login" varchar,
  "name" varchar,
  "birthday" Date
);

CREATE TABLE IF NOT EXISTS "Film"(
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" varchar,
  "releaseDate" Date,
  "duration" int,
  "rating_id" int,
  FOREIGN KEY ("rating_id") REFERENCES "Rating" ("id")
);

CREATE TABLE IF NOT EXISTS "FilmLikes"(
  "film_id" int,
  "user_id" int,
  PRIMARY KEY ("film_id", "user_id"),
  FOREIGN KEY ("film_id") REFERENCES "Film" ("id"),
  FOREIGN KEY ("user_id") REFERENCES "User" ("id")
);

CREATE TABLE IF NOT EXISTS "Friends"(
  "user_id" int,
  "friend_id" int,
  "confirmed" boolean,
  PRIMARY KEY ("user_id", "friend_id"),
  FOREIGN KEY ("user_id") REFERENCES "User" ("id"),
  FOREIGN KEY ("friend_id") REFERENCES "User" ("id")
);

CREATE TABLE IF NOT EXISTS "FilmGenre"(
  "film_id" int,
  "genre_id" int,
  PRIMARY KEY ("film_id", "genre_id"),
  FOREIGN KEY ("film_id") REFERENCES "Film" ("id"),
  FOREIGN KEY ("genre_id") REFERENCES "Genre" ("id")
);







